version: '3.8'

services:
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    build:
      context: ./webapp
    ports:
      - "3000:3000"

volumes:
  redis-data:
  postgres-data: